// Mock data for the e-learning platform

export const COURSESS = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    category: "Development",
    level: "Beginner",
    price: 89.99,
    rating: 4.8,
    students: 12450,
    duration: "42 hours",
    image: "https://images.unsplash.com/photo-1565229284535-2cbbe3049123?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Sarah Johnson",
    instructorAvatar: "https://images.unsplash.com/photo-1755548413928-4aaeba7c740e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: "Bestseller",
    badgeColor: "#FF7A00",
    description: "Learn HTML, CSS, JavaScript, React and more to become a full-stack developer.",
    modules: 12,
    lessons: 148,
    progress: 65,
  },
  {
    id: 2,
    title: "Data Science & Machine Learning",
    category: "Data Science",
    level: "Intermediate",
    price: 119.99,
    rating: 4.9,
    students: 8920,
    duration: "56 hours",
    image: "https://images.unsplash.com/photo-1762279389083-abf71f22d338?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Dr. Michael Chen",
    instructorAvatar: "https://images.unsplash.com/photo-1758691736975-9f7f643d178e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: "Top Rated",
    badgeColor: "#7F3FBF",
    description: "Master Python, TensorFlow, and machine learning algorithms from scratch.",
    modules: 16,
    lessons: 210,
    progress: 30,
  },
  {
    id: 3,
    title: "Digital Marketing Mastery",
    category: "Marketing",
    level: "Beginner",
    price: 69.99,
    rating: 4.7,
    students: 15300,
    duration: "28 hours",
    image: "https://images.unsplash.com/photo-1769596722541-40dedee6789d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Emma Williams",
    instructorAvatar: "https://images.unsplash.com/photo-1645664747204-31fee58898dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: "New",
    badgeColor: "#28A745",
    description: "SEO, social media, email marketing and paid ads to grow any business.",
    modules: 8,
    lessons: 96,
    progress: 80,
  },
  {
    id: 4,
    title: "Graphic Design Fundamentals",
    category: "Design",
    level: "Beginner",
    price: 79.99,
    rating: 4.6,
    students: 6750,
    duration: "32 hours",
    image: "https://images.unsplash.com/photo-1759150467548-5a97257e583a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Carlos Rivera",
    instructorAvatar: "https://images.unsplash.com/photo-1758691736975-9f7f643d178e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: null,
    badgeColor: null,
    description: "Adobe Photoshop, Illustrator and design principles for beginners.",
    modules: 10,
    lessons: 120,
    progress: 0,
  },
  {
    id: 5,
    title: "Business Management & Leadership",
    category: "Business",
    level: "Advanced",
    price: 149.99,
    rating: 4.8,
    students: 4200,
    duration: "38 hours",
    image: "https://images.unsplash.com/photo-1565688527174-775059ac429c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Dr. Linda Foster",
    instructorAvatar: "https://images.unsplash.com/photo-1755548413928-4aaeba7c740e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: "Premium",
    badgeColor: "#4A90E2",
    description: "Strategic management, leadership skills, and organizational behavior.",
    modules: 14,
    lessons: 165,
    progress: 0,
  },
  {
    id: 6,
    title: "Photography & Video Production",
    category: "Creative",
    level: "Intermediate",
    price: 94.99,
    rating: 4.7,
    students: 5600,
    duration: "35 hours",
    image: "https://images.unsplash.com/photo-1758612214917-81d7956c09de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    instructor: "Alex Thompson",
    instructorAvatar: "https://images.unsplash.com/photo-1645664747204-31fee58898dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    badge: null,
    badgeColor: null,
    description: "Camera techniques, lighting, editing and storytelling for creatives.",
    modules: 11,
    lessons: 132,
    progress: 0,
  },
];

export const CATEGORIES = [
  { id: 1, name: "Development", icon: "💻", count: 234, color: "#4A90E2" },
  { id: 2, name: "Data Science", icon: "📊", count: 156, color: "#7F3FBF" },
  { id: 3, name: "Marketing", icon: "📣", count: 189, color: "#FF7A00" },
  { id: 4, name: "Design", icon: "🎨", count: 142, color: "#28A745" },
  { id: 5, name: "Business", icon: "💼", count: 198, color: "#4A90E2" },
  { id: 6, name: "Creative", icon: "🎬", count: 87, color: "#7F3FBF" },
  { id: 7, name: "Language", icon: "🌍", count: 112, color: "#FF7A00" },
  { id: 8, name: "Health", icon: "🏃", count: 65, color: "#28A745" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "James Anderson",
    role: "Software Engineer at Google",
    avatar: "https://images.unsplash.com/photo-1758691736975-9f7f643d178e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    text: "LearnHub completely transformed my career. The Web Development Bootcamp gave me all the skills I needed to land my dream job at Google.",
    rating: 5,
    course: "Web Development Bootcamp",
  },
  {
    id: 2,
    name: "Priya Sharma",
    role: "Data Scientist at Microsoft",
    avatar: "https://images.unsplash.com/photo-1645664747204-31fee58898dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    text: "The Data Science course was incredibly comprehensive. The hands-on projects and mentorship made all the difference.",
    rating: 5,
    course: "Data Science & ML",
  },
  {
    id: 3,
    name: "Marcus Johnson",
    role: "Marketing Director",
    avatar: "https://images.unsplash.com/photo-1755548413928-4aaeba7c740e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    text: "I went from zero marketing knowledge to running a $500K campaign in 6 months. The platform's quality is unmatched.",
    rating: 5,
    course: "Digital Marketing Mastery",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "10 Skills Every Developer Needs in 2026",
    category: "Development",
    author: "Sarah Johnson",
    date: "March 1, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1565229284535-2cbbe3049123?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    excerpt: "The tech industry is evolving rapidly. Here are the top 10 skills that will make you stand out...",
  },
  {
    id: 2,
    title: "How to Land Your First Data Science Job",
    category: "Data Science",
    author: "Dr. Michael Chen",
    date: "February 25, 2026",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1762279389083-abf71f22d338?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    excerpt: "Breaking into data science can be challenging. This guide covers everything you need to know...",
  },
  {
    id: 3,
    title: "The Future of Digital Marketing",
    category: "Marketing",
    author: "Emma Williams",
    date: "February 18, 2026",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1769596722541-40dedee6789d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    excerpt: "AI, automation, and personalization are reshaping marketing. Here's what to expect...",
  },
  {
    id: 4,
    title: "Design Trends Shaping UX in 2026",
    category: "Design",
    author: "Carlos Rivera",
    date: "February 10, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1759150467548-5a97257e583a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    excerpt: "From glassmorphism to AI-generated interfaces, here's what's trending in design...",
  },
  {
    id: 5,
    title: "Building Remote Teams That Actually Work",
    category: "Business",
    author: "Dr. Linda Foster",
    date: "February 5, 2026",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1758691736975-9f7f643d178e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=100",
    excerpt: "Remote work is here to stay. Learn the strategies top companies use to manage distributed teams...",
  },
  {
    id: 6,
    title: "Mastering Photography on a Budget",
    category: "Creative",
    author: "Alex Thompson",
    date: "January 28, 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1758612214917-81d7956c09de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    excerpt: "You don't need expensive gear to take stunning photos. Here's how to maximize what you have...",
  },
];

export const TEAM_MEMBERS = [
  {
    id: 1,
    name: "Dr. Angela Roberts",
    role: "CEO & Co-Founder",
    image: "https://images.unsplash.com/photo-1645664747204-31fee58898dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=200",
    bio: "Former EdTech executive with 15+ years in education technology.",
  },
  {
    id: 2,
    name: "David Kim",
    role: "CTO & Co-Founder",
    image: "https://images.unsplash.com/photo-1758691736975-9f7f643d178e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=200",
    bio: "Full-stack engineer with expertise in scalable learning platforms.",
  },
  {
    id: 3,
    name: "Sofia Martinez",
    role: "Head of Content",
    image: "https://images.unsplash.com/photo-1755548413928-4aaeba7c740e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=200",
    bio: "Curriculum designer with a passion for accessible education.",
  },
  {
    id: 4,
    name: "Marcus Thompson",
    role: "Head of Growth",
    image: "https://images.unsplash.com/photo-1758612214917-81d7956c09de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=200",
    bio: "Growth hacker who scaled platforms to millions of users.",
  },
];

export const MODULES = [
  { id: 1, title: "Introduction to Web Development", lessons: 8, duration: "2h 30m", completed: true },
  { id: 2, title: "HTML Fundamentals", lessons: 12, duration: "3h 45m", completed: true },
  { id: 3, title: "CSS Styling & Layouts", lessons: 15, duration: "4h 20m", completed: true },
  { id: 4, title: "JavaScript Basics", lessons: 18, duration: "5h 10m", completed: false, current: true },
  { id: 5, title: "Advanced JavaScript", lessons: 14, duration: "4h 50m", completed: false },
  { id: 6, title: "React.js Framework", lessons: 20, duration: "6h 30m", completed: false },
  { id: 7, title: "Node.js & Backend", lessons: 16, duration: "5h 20m", completed: false },
  { id: 8, title: "Databases & APIs", lessons: 13, duration: "4h 10m", completed: false },
];

export const ADMIN_STATS = {
  totalUsers: 48520,
  totalCourses: 1240,
  totalRevenue: 892450,
  activeLearners: 12890,
  completionRate: 73,
  newUsersThisMonth: 1850,
};

export const SUBSCRIPTION_PLANS = [
  {
    id: 1,
    name: "Starter",
    price: 29,
    period: "month",
    color: "#4A90E2",
    popular: false,
    features: [
      "Access to 50+ courses",
      "HD video quality",
      "Certificate of completion",
      "Mobile app access",
      "Community forum",
    ],
    disabled: ["Priority support", "Offline downloads", "1-on-1 mentoring"],
  },
  {
    id: 2,
    name: "Pro",
    price: 59,
    period: "month",
    color: "#7F3FBF",
    popular: true,
    features: [
      "Access to 500+ courses",
      "4K video quality",
      "Certificate of completion",
      "Mobile app access",
      "Community forum",
      "Priority support",
      "Offline downloads",
    ],
    disabled: ["1-on-1 mentoring"],
  },
  {
    id: 3,
    name: "Enterprise",
    price: 149,
    period: "month",
    color: "#FF7A00",
    popular: false,
    features: [
      "Unlimited course access",
      "4K video quality",
      "Certificate of completion",
      "Mobile app access",
      "Community forum",
      "Priority support",
      "Offline downloads",
      "1-on-1 mentoring",
    ],
    disabled: [],
  },
];
